name = "Fabricate"
author = "topongo"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c024b971dd832874ec2b7d3f5429cb04b5050d0fbee62400d7720efb109f23f"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
