name = "Fabricate"
author = "topongo"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db71b54d17b49d558ec16198fd6e8ff3c5e08655ce386fb6f1301a3a3de3f270"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
