name = "Fabricate"
author = "topongo"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "355bff4736aac2642050d06ae9e978ab227beba61bb2169e95fa56c88711576b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
